name: Build, Commit, Tag & Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'dist/**'

permissions:
  contents: write

jobs:
  build-and-release:
    uses: actionsforge/actions/.github/workflows/node-action-tag-and-release.yml@main
    with:
      node-version: '20'
      build: true
      commit-dist: true
      create-release: true
      update-major-tag: true
    secrets: inherit
